### ISSUE TITLE
组件有错误，不知道是不是转换造成的

### ISSUE THREAD

**Issue by codering** [fis-components/rc-calendar#1]
只是引入组件

``` js
import Calendar from 'rc-calendar';
```

然后打开浏览器，错误信息是

```
Uncaught Error: Invariant Violation: ReactClassInterface: You are attempting to define `default` on your component more than once. This conflict may be due to a mixin.
```

我调试时看到错误是  /components/rc-calendar/lib/Calendar.js 83行， 看不出问题。。。
![2015-12-31 16 37 57](https://cloud.githubusercontent.com/assets/2271825/12062724/f2442012-afdc-11e5-9a06-ed492f3f3a8e.png)

**Comment by 2betop** [comment]
83 行是这样的，你确定版本是一致的？https://github.com/fis-components/rc-calendar/blob/master/lib/Calendar.js#L83

**Comment by codering** [comment]
恩，源码是一样的，我是在浏览器截图的，包裹了define就变成第83行了。

**Comment by 2betop** [comment]
我也没看出来。有空我使用下这个组件

**Comment by 2betop** [comment]
我也遇到这个问题

**Comment by 2betop** [comment]
跟新下 mod.js ，看似是没问题了，还需要进一步确定。

```
if (mod.exports && !mod.exports['default']) {
            Object.defineProperty(mod.exports, 'default', {
                value: mod.exports
            });
        }
```

**Comment by codering** [comment]
ok了，谢谢
